name: Android APK Build (sky-rus)

on:
  push:
    branches: [ "sky-rus" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Pre-install dependencies
      run: pip install aqtinstall

    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        target: 'android'
        arch: 'android_arm64_v8a'
        setup-python: 'false'

    - name: Build QGC
      run: |
        mkdir build && cd build
        qmake ../qgroundcontrol.pro -spec android-clang CONFIG+=release
        make -j$(nproc)
        make install INSTALL_ROOT=android-build
        androiddeployqt --input android-libQGroundControl.so-deployment-settings.json --output android-build --gradle

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: QGC-RM510-Build
        path: build/android-build/build/outputs/apk/release/*.apk
        retention-days: 3
